### ISSUE TITLE
simit-check fails on documentation example

### ISSUE THREAD

**Issue by dahtah** [simit-lang/simit#29]
The following bit of code is taken directly from the documentation:
```
element Point
  x : vector[3](float);
  v : vector[3](float);
end

func move(p : Point)
  p.x(0) += 1.0;  % p.x += [1.0, 0.0, 0.0];
end
```
simit-check returns:
   Error: expected an expression but got '=', at 7:11

Changing p.x(0) += 1.0; to p.x(0) + p.x(0) + 1.0;  gives a different error:
   Error: assignment target is not writable, at 7:3-8

**Comment by stephenchouca** [comment]
Thanks for pointing this out! As alluded to in #7, the `+=` operator is not currently supported by the Simit compiler. The same behavior (in this context at least) can be achieved by replacing that line with `p.x(0) = p.x(0) + 1.0` as you suggested.

The "assignment target is not writable" error is actually due to a typo in the documentation. The declaration of `p` needs to be preceded by the keyword `inout` to indicate that `p` is not a read-only argument (by default, function arguments are read-only and cannot be updated). The documentation will be updated accordingly.

The following should compile:

```
element Point
  x : vector[3](float);
  v : vector[3](float);
end

func move(inout p : Point)
  p.x(0) = p.x(0) + 1.0;  % p.x += [1.0, 0.0, 0.0];
end
```

**Comment by fredrikbk** [comment]
I replaced `+=` in that example with `p.x(0) = p.x(0) + 1.0;` as a temporary fixed. When #7 is fixed we'll change it back.

Thanks for letting us know about this!
